/** @type {import('tailwindcss').Config} */
module.exports = {
  purge: [],
  darkMode: false, // or 'media' or 'class'
  theme: {
    screens: {
      sm: "639px",
      md: "1159px",
      lg: "1539px",
    },
    colors: {
      "passion-green-vibrant": "#00a862",
      "passion-green-soft": "#66cda5",
      "passion-green-light": "#cceee1",
      "foundational-green-vibrant": "#004731",
      "foundational-green-soft": "#688a81",
      "foundational-green-light": "#c8d7d3",
      "kindness-green-vibrant": "#26d07c",
      "kindness-green-soft": "#7de3b0",
      "kindness-green-light": "#d4f6e5",
      "dragonfruit-vibrant": "#671575",
      "dragonfruit-soft": "#a473ac",
      "dragonfruit-light": "#e1d0e3",
      "papaya-vibrant": "#ff8674",
      "papaya-soft": "#ffb6ac",
      "papaya-light": "#ffe7e3",
      "saffron-vibrant": "#ffa300",
      "saffron-soft": "#ffc866",
      "saffron-light": "#ffedcc",
      "blueberry-vibrant": "#0076a8",
      "blueberry-soft": "#66adcb",
      "blueberry-light": "#cce4ee",
      black: "#101820",
      "dark-gray": "#444444",
      "medium-gray": "#707070",
      "light-gray": "#f8f8f8",
      white: "#ffffff",
      "black-soft": "#7b8187",
      "black-light": "#cacacc",
      "gold-vibrant": "#c6893f",
      "gold-soft": "#e8c29b",
      "gold-light": "#F4E5D6",
      "platinum-vibrant": "#A7A8AA",
      "platinum-soft": "#D2D2D5",
      "platinum-light": "#ECECEC",
      "blue-vibrant": "#004159",
      "blue-soft": "#7498A1",
      "blue-light": "#C6D5D9",
    },
    extend: {},
  },
  variants: {
    extend: {},
  },
  plugins: [],
};
